import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "./components/Navbar";
import Bannar from "./components/Bannar";
import AboutUs from "./components/Aboutus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
      
        <main className="h-screen h-max-[600px]">{children}</main>

        {/* <footer className="text-center bg-stone-500">
          Awesome NextJS Project
        </footer> */}
      </body>
    </html>
  );
}
