import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "./components/Navbar";
import Providers from "./Redux/Providers";
import Footer from "./components/Footer";
import SessionProviderWrapper from "./components/SessionProviderWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Client-only providers must be wrapped like this */}
        <SessionProviderWrapper>
          <Providers>
            <NavBar />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </Providers>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
